# Dependabot configuration for automated dependency updates
version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "wonderolabisi"
    assignees:
      - "wonderolabisi"
    commit-message:
      prefix: "deps"
      include: "scope"
