name: flutter_devsecops_template
description: A Flutter DevSecOps template app.

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  # or the latest version
  
flutter:
  uses-material-design: true
