name: flutter_devsecops_template
description: A Flutter DevSecOps template app.

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'  # Updated for flutter_lints ^6.0.0
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  # Works with Dart SDK 3.8.0+
  
flutter:
  uses-material-design: true
